# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: JFrogGenericArtifacts@1
  inputs:
    command: 'Download'
    connection: 'hts2-token'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "pruthvi-generic-local/*.gpg",
            "target": "./"
          }
        ]
      }
    failNoOp: true